### ISSUE TITLE
Panics on start

### ISSUE THREAD

**Issue by JBBgameich** [flathub/com.github.flxzt.rnote#26]
Since the latest update, RNote crashes for me with the following message:
```
thread 'main' panicked at 'Source property state expected type GVariant but transform_from function returned gchararray', /run/build/rnote/vendor/glib/src/object.rs:3756:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by flxzt** [comment]
argh, okay. Usually such issues should reported in the upstream repo, but whatever. Can you run it with ` --env=RUST_LOG=rnote=debug --env=RUST_BACKTRACE=1` ?

**Comment by JBBgameich** [comment]
I think I'm missing debug information in the flatpak, the stack baktrace is empty.

**Comment by flxzt** [comment]
should be fixed, see https://github.com/flxzt/rnote/issues/568

**Comment by JBBgameich** [comment]
Thanks!
